import { mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { renderToMarkdown, renderToText } from "md4x";
import type { DocsManager, FlatEntry } from "./manager.ts";

export interface ExportOptions {
  /** Custom filter callback. Return false to skip an entry. Default: skip stubs (page === false) */
  filter?: (entry: FlatEntry) => boolean;

  /** Compile markdown to plain text using md4x. Default: false */
  plainText?: boolean;

  /** Filename for the generated table of contents. Default: "README.md" */
  tocFile?: string;

  /** Title for the table of contents. Default: root entry title or "Table of Contents" */
  title?: string;
}

/** Paths to skip during export (generated by source, not actual docs) */
const IGNORED_PATHS = new Set(["/llms.txt", "/llms-full.txt"]);

/**
 * Export documentation entries to a local filesystem directory as flat `.md` files.
 *
 * Each entry is written to `<dir>/<path>.md`. Directory stubs (`page === false`)
 * are skipped by default unless a custom `filter` is provided.
 *
 * A `README.md` table of contents is generated at the root of the output directory.
 */
export async function exportDocsToFS(
  manager: DocsManager,
  dir: string,
  options: ExportOptions = {},
): Promise<void> {
  const rootEntry = manager.flat.find((f) => f.entry.path === "/");
  const tocTitle = options.title ?? rootEntry?.entry.title ?? "Table of Contents";
  const tocLines: string[] = [`# ${tocTitle}`, ""];
  const writtenFiles = new Set<string>();

  for (const flat of manager.flat) {
    if (options.filter ? !options.filter(flat) : flat.entry.page === false) continue;

    if (IGNORED_PATHS.has(flat.entry.path)) continue;

    let content = await manager.getContent(flat);
    if (content === undefined) continue;

    const cleanContent = options.plainText ? renderToText(content) : renderToMarkdown(content);

    const filePath =
      flat.entry.path === "/"
        ? "/index.md"
        : flat.entry.path.endsWith(".md")
          ? flat.entry.path
          : `${flat.entry.path}.md`;
    const dest = join(dir, filePath);

    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, cleanContent, "utf8");
    writtenFiles.add(filePath.slice(1)); // strip leading /

    const indent = "  ".repeat(flat.depth);
    const desc = flat.entry.description ? `: ${flat.entry.description}` : "";
    tocLines.push(`${indent}- [${flat.entry.title}](.${filePath})${desc}`);
  }

  // Write table of contents, prefix with _ if it conflicts with an exported file
  let tocFile = options.tocFile ?? "README.md";
  if (writtenFiles.has(tocFile)) {
    tocFile = `_${tocFile}`;
  }
  await writeFile(join(dir, tocFile), tocLines.join("\n") + "\n", "utf8");
}
