import { mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { renderToMarkdown, renderToText } from "md4x";
import { Collection } from "./collection.ts";
import type { FlatEntry } from "./collection.ts";
import type { NavEntry } from "./nav.ts";
import type { Source } from "./sources/_base.ts";
import { resolveSource } from "./source.ts";

export interface ExportOptions {
  /** Custom filter callback. Return false to skip an entry. Default: skip stubs (page === false) */
  filter?: (entry: FlatEntry) => boolean;

  /** Compile markdown to plain text using md4x. Default: false */
  plainText?: boolean;

  /** Filename for the generated table of contents. Default: "README.md" */
  tocFile?: string;

  /** Title for the table of contents. Default: root entry title or "Table of Contents" */
  title?: string;
}

/**
 * High-level export: resolve source, load, and export in one call.
 *
 * ```ts
 * await exportSource("./docs", "./dist/docs");
 * await exportSource("gh:unjs/h3", "./dist/h3-docs");
 * await exportSource("npm:h3", "./dist/h3-docs", { plainText: true });
 * await exportSource("https://h3.unjs.io", "./dist/h3-docs");
 * ```
 */
export async function exportSource(
  input: string | Source,
  dir: string,
  options: ExportOptions = {},
): Promise<Collection> {
  const source = typeof input === "string" ? resolveSource(input) : input;
  const collection = new Collection(source);
  await collection.load();
  await mkdir(dir, { recursive: true });
  await writeCollection(collection, dir, options);
  return collection;
}

/** Paths to skip during export (generated by source, not actual docs) */
const IGNORED_PATHS = new Set(["/llms.txt", "/llms-full.txt"]);

/**
 * Export documentation entries to a local filesystem directory as flat `.md` files.
 *
 * Each entry is written to `<dir>/<prefix>.<slug>.md` (or `<dir>/<prefix>.<slug>/index.md`
 * for directory index pages). Navigation order is preserved via numeric prefixes on
 * directories and files (e.g., `1.guide/`, `2.getting-started.md`) so the nav scanner
 * can infer order without additional metadata files.
 *
 * A `README.md` table of contents is generated at the root of the output directory.
 */
export async function writeCollection(
  collection: Collection,
  dir: string,
  options: ExportOptions = {},
): Promise<void> {
  const rootEntry = collection.flat.find((f) => f.entry.path === "/");
  const tocTitle = options.title ?? rootEntry?.entry.title ?? "Table of Contents";
  const tocLines: string[] = [`# ${tocTitle}`, ""];
  const writtenFiles = new Set<string>();

  // Build a map from nav path → numbered filesystem path
  const pathMap = new Map<string, string>();
  buildNumberedPaths(collection.tree, "", pathMap);

  // Collect directory paths (entries with children) to fix file placement
  const dirPaths = new Set<string>();
  collectDirPaths(collection.tree, dirPaths);

  for (const flat of collection.flat) {
    if (options.filter ? !options.filter(flat) : flat.entry.page === false) continue;

    if (IGNORED_PATHS.has(flat.entry.path)) continue;

    let content = await collection.getContent(flat);
    if (content === undefined) continue;

    const cleanContent = options.plainText ? renderToText(content) : renderToMarkdown(content);

    const numberedPath = pathMap.get(flat.entry.path) ?? flat.entry.path;
    const isIndex = flat.entry.path === "/" || dirPaths.has(flat.entry.path);
    const filePath = isIndex
      ? flat.entry.path === "/"
        ? "/index.md"
        : `${numberedPath}/index.md`
      : numberedPath.endsWith(".md")
        ? numberedPath
        : `${numberedPath}.md`;
    const dest = join(dir, filePath);

    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, cleanContent, "utf8");
    writtenFiles.add(filePath.slice(1)); // strip leading /

    const indent = "  ".repeat(flat.depth);
    const desc = flat.entry.description ? `: ${flat.entry.description}` : "";
    tocLines.push(`${indent}- [${flat.entry.title}](.${filePath})${desc}`);
  }

  // Write table of contents, prefix with _ if it conflicts with an exported file
  let tocFile = options.tocFile ?? "README.md";
  if (writtenFiles.has(tocFile)) {
    tocFile = `_${tocFile}`;
  }
  await writeFile(join(dir, tocFile), tocLines.join("\n") + "\n", "utf8");
}

/** Collect all paths that are directories (have children in the tree). */
function collectDirPaths(entries: NavEntry[], set: Set<string>): void {
  for (const entry of entries) {
    if (entry.children?.length) {
      set.add(entry.path);
      collectDirPaths(entry.children, set);
    }
  }
}

/**
 * Build a map from nav path → numbered filesystem path.
 * Uses sibling index as the numeric prefix (e.g., `/guide` → `/1.guide`).
 */
function buildNumberedPaths(
  entries: NavEntry[],
  parentPath: string,
  map: Map<string, string>,
): void {
  for (const [i, entry] of entries.entries()) {
    const slug = entry.slug || "index";
    const numbered = `${parentPath}/${i}.${slug}`;
    map.set(entry.path, numbered);
    if (entry.children?.length) {
      buildNumberedPaths(entry.children, numbered, map);
    }
  }
}
